### ISSUE TITLE
Commit not disabled on Whse Shipment Post

### ISSUE THREAD

**Issue by vdevmt** [microsoft/ALAppExtensions#20080]
At the end of "Whse.-Post Shipment" codeunit there is a Commit not handled with SuppressCommit parameter.

    local procedure "Code"()
    begin
      [...]

       OnAfterPostWhseShipment(WhseShptHeader);

        **Commit()**
        PrintDocuments();
        Clear(WMSMgt);
        Clear(WhseJnlRegisterLine);

        WhseShptLine.Reset();
   end;

Maybe this code could be changed in:

    local procedure "Code"()
    begin
      [...]

       OnAfterPostWhseShipment(WhseShptHeader);

        **if (not SuppressCommit) or Print then
              Commit()**

        PrintDocuments();
        Clear(WMSMgt);
        Clear(WhseJnlRegisterLine);

        WhseShptLine.Reset();
   end;

**Comment by AlexanderYakunin** [comment]
This is already fixed for version 21.

**Comment by vdevmt** [comment]
I'm working on version 21.0.46256 and this unmanaged commit still exists (Line 141):

local procedure "Code"()
begin
  [...]

   OnAfterPostWhseShipment(WhseShptHeader);

    **Commit()**
    PrintDocuments();
    Clear(WMSMgt);
    Clear(WhseJnlRegisterLine);

    WhseShptLine.Reset();

  [...]
end;

**Comment by AlexanderYakunin** [comment]
When you created requests on August 30, it was already too late for 21.0 release, as our Engineering Complete date was August 24. This fix went into 21.x branch on Sep 22 and will be in 21.1.
