### ISSUE TITLE
CommentLines not renamed when Customer is renamed

### ISSUE THREAD

**Issue by ELeifeld** [microsoft/ALAppExtensions#8328]
When renaming a Customer record, CommentLine records are not renamed! This issue exists since 16.0.
The reason are missing table relations in table 97 on field 2 ("No.")

it should be:

`TableRelation = IF ("Table Name" = CONST("G/L Account")) "G/L Account"
            ELSE
            IF ("Table Name" = CONST(Customer)) Customer
            ELSE
            IF ("Table Name" = CONST(Vendor)) Vendor
            ELSE
            IF ("Table Name" = CONST(Item)) Item
            ELSE
            IF ("Table Name" = CONST(Resource)) Resource
            ELSE
            IF ("Table Name" = CONST(Job)) Job
            ELSE
            IF ("Table Name" = CONST("Resource Group")) "Resource Group"
            ELSE
            IF ("Table Name" = CONST("Bank Account")) "Bank Account"
            ELSE
            IF ("Table Name" = CONST(Campaign)) Campaign
            ELSE
            IF ("Table Name" = CONST("Fixed Asset")) "Fixed Asset"
            ELSE
            IF ("Table Name" = CONST(Insurance)) Insurance
            ELSE
            IF ("Table Name" = CONST("IC Partner")) "IC Partner"`

i fixed it by modifiing the field in extension - but it has to be fixed in standard..

**Comment by AlexanderYakunin** [comment]
This is already fixed but differently.

**Comment by ELeifeld** [comment]
How is it fixed? In which version is it fixed? I tried out in 16.4 it was not fixed.

**Comment by AlexanderYakunin** [comment]
Using CommentLine.RenameCommentLine(CommentLine."Table Name"::XXX, xRec."No.", "No.") in OnRename trigger for affected tables. It will be in next updates.
